language: java
jdk:
  - openjdk8
sudo: required
branches:
  only:
    - develop
services:
  - docker
env:
  - TAG="$(git rev-parse --short HEAD)"
notifications:
  email:
    - sumusb34@gmail.com
  on_success: always
  on_failure: always
before_script:
  - pip install --user awscli
script:
  - ls
  - chmod +x ./gradlew
  - ./gradlew bootJar -Ppassword=${ENCRIPTION_KEY}
  - eval $(aws ecr get-login --no-include-email)
  - docker build -t 989243724240.dkr.ecr.ap-northeast-2.amazonaws.com/wepet:${TAG} .
  - docker push 989243724240.dkr.ecr.ap-northeast-2.amazonaws.com/wepet/wepet:${TAG}
